[package]
name = "arclightning_backend"
version = "0.1.0"
authors = ["sremedios <sam.remedios@gmail.com>"]

[dependencies]
hyper = "0.12"
futures = "0.1"
serde_json = "1"
serde = "1.0"
serde_derive = "1.0"
toml = "0.4"
