[package]
name = "arclightning_backend"
version = "0.1.0"
authors = ["sremedios <sam.remedios@gmail.com>"]

[dependencies]
failure = "0.1"
futures = "0.1"
hyper = "0.12"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1"
toml = "0.4"
