listen_port = 3000
static_dir = "..\\arclightning_frontend"
password = "$2y$04$eLEyVov359aq6Oj9SImPnu2B0xKMglzI1Dk3Epvf.9X3OsLfxQ7yO"
[games.melty_blood]
name = "Melty Blood"
description = "fighter with waifus"
genres = ["fighter", "anime", "2d"]
thumbnail_path = "path/to/melty_blood/thumbnail"

[games.touhou_123]
name = "Touhou"
description = "bullet hell with waifus"
genres = ["bullet hell", "anime"]
thumbnail_path = "path/to/touhou/thumbnail"
