[games.touhou_123]
name = "Touhou"
description = "bullet hell with waifus"
genres = ["bullet hell", "anime"]
thumbnail_path = "path/to/touhou/thumbnail"
exe_path = "test_files\\touhou_game.exe"
exe_args = ["arg1", "arg2"]

[games.melty_blood]
name = "Melty Blood"
description = "fighter with waifus"
genres = ["fighter", "anime", "2d"]
thumbnail_path = "path/to/melty_blood/thumbnail"
exe_path = "test_files\\melty_blood_game.exe"
exe_args = ["arg1", "arg2"]

[server_config]
static_dir = "..\\arclightning_frontend"
listen_port = 3000
